<a href="https://colab.research.google.com/github/bimbeo/Web/blob/master/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://www.w3resource.com/w3r_images/linear-algebra-image.svg)

**1, Viết chương trình NumPy để tính phép nhân của hai ma trận đã cho.**

**Write a NumPy program to compute the multiplication of two given matrixes.**

![alt text](https://www.w3resource.com/w3r_images/linear-algebra-image-exercise-1.png)

In [2]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("Original matrix: ")
print(p)
print(q)
result1 = np.dot(p, q)
print("Result of the said matrix multiplication: ")
print(result1)

Original matrix: 
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Result of the said matrix multiplication: 
[[1 2]
 [3 4]]


**2, Viết chương trình NumPy để tính tích ngoài của hai vectơ đã cho.**

**Write a NumPy program to compute the outer product of two given vectors.**

![alt text](https://www.w3resource.com/w3r_images/linear-algebra-image-exercise-2.png)

In [3]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result = np.outer(p, q)
print("Outrer product of the said two vector: ")
print(result)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Outrer product of the said two vector: 
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


**3, Viết chương trình NumPy để tính tích vector của hai vectơ đã cho.**

**Write a NumPy program to compute the cross product of two given vectors.**

![alt text](https://www.w3resource.com/w3r_images/linear-algebra-image-exercise-3.png)

In [4]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.cross(p, q)
result2 = np.cross(q, p)
print("cross product of the said two vectors(p, q): ")
print(result1)
print("cross product of the said two vector(q, p): ")
print(result2)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
cross product of the said two vectors(p, q): 
[ 2 -3]
cross product of the said two vector(q, p): 
[-2  3]


**4, Viết chương trình NumPy để tính định thức của một mảng vuông đã cho.**

**Write a NumPy program to compute the determinant of a given square array.**

![alt text](https://www.w3resource.com/w3r_images/linear-algebra-image-exercise-4.png)



In [5]:
from numpy import linalg as LA
a = np.array([[1,0], [1,2]])
print("Original 2-d array")
print(a)
print("Determinant of the said 2-D array: ")
print(np.linalg.det(a))

Original 2-d array
[[1 0]
 [1 2]]
Determinant of the said 2-D array: 
2.0


**5, Viết chương trình NumPy để đánh giá quy ước tổng kết Einstein Einstein của hai mảng đa chiều đã cho.**

**Write a NumPy program to evaluate Einstein’s summation convention of two given multidimensional arrays.**



In [6]:
a = np.array([1,2,3])
b = np.array([0,1,0])
print("Original 1-d arrays:")
print(a)
print(b)
result =  np.einsum("n,n", a, b)
print("Einstein’s summation convention of the said arrays:")
print(result)
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Original Higher dimension:")
print(x)
print(y)
result = np.einsum("mk,kn", x, y)
print("Einstein’s summation convention of the said arrays:")
print(result)

Original 1-d arrays:
[1 2 3]
[0 1 0]
Einstein’s summation convention of the said arrays:
2
Original Higher dimension:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Einstein’s summation convention of the said arrays:
[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]


**6, Viết chương trình NumPy để tính tích trong của vectơ cho mảng 1-D (không có liên hợp phức tạp) và ở chiều cao hơn.**

**Write a NumPy program to compute the inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension.**



In [8]:
a = np.array([1,2,5])
b = np.array([2,1,0])
print("Original 1-d arrays:")
print(a)
print(b)
result = np.inner(a, b)
print("Inner product of the said vectors:")
print(result)
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Higher dimension arrays:")
print(x)
print(y)
result = np.inner(x, y)
print("Inner product of the said vectors:")
print(result)

Original 1-d arrays:
[1 2 5]
[2 1 0]
Inner product of the said vectors:
4
Higher dimension arrays:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Inner product of the said vectors:
[[ 14  23  32]
 [ 50  86 122]
 [ 86 149 212]]


**7, Viết chương trình NumPy để tính toán các giá trị riêng và các hàm riêng bên phải của một mảng vuông đã cho.**

**Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.**



In [9]:
m = np.mat("3 -2; 1 0")
print("Original matrix: ")
print("a\n", m)
w, v = np.linalg.eig(m)
print("Eigenvalues of the said matrix", w)
print("Eigenvalues of the said matrix", v)

Original matrix: 
a
 [[ 3 -2]
 [ 1  0]]
Eigenvalues of the said matrix [2. 1.]
Eigenvalues of the said matrix [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


**8, Viết chương trình NumPy để tính toán sản phẩm Kronecker của hai mảng mulitdimension đã cho.**


**Write a NumPy program to compute the Kronecker product of two given mulitdimension arrays.**

![alt text](https://www.w3resource.com/w3r_images/linear-algebra-image-exercise-8.png)


In [10]:
a = np.array([1,2,3])
b = np.array([0,1,0])
print("Original 1-d arrays:")
print(a)
print(b)
result =  np.kron(a, b)
print("Kronecker product of the said arrays:")
print(result)
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Original Higher dimension:")
print(x)
print(y)
result = np.kron(x, y)
print("Kronecker product  of the said arrays:")
print(result)

Original 1-d arrays:
[1 2 3]
[0 1 0]
Kronecker product of the said arrays:
[0 1 0 0 2 0 0 3 0]
Original Higher dimension:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Kronecker product  of the said arrays:
[[ 0  0  0  3  4  5  6  8 10]
 [ 0  0  0  6  7  8 12 14 16]
 [ 0  0  0  9 10 11 18 20 22]
 [ 9 12 15 12 16 20 15 20 25]
 [18 21 24 24 28 32 30 35 40]
 [27 30 33 36 40 44 45 50 55]
 [18 24 30 21 28 35 24 32 40]
 [36 42 48 42 49 56 48 56 64]
 [54 60 66 63 70 77 72 80 88]]


**9, Viết chương trình NumPy để tính số điều kiện của một ma trận đã cho.**

**Write a NumPy program to compute the condition number of a given matrix.**



In [11]:
a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
print("Original matrix:")
print(a)
print("The condition number of the said matrix:")
print(LA.cond(a))

Original matrix:
[[ 1  0 -1]
 [ 0  1  0]
 [ 1  0  1]]
The condition number of the said matrix:
1.4142135623730951


**10, Viết chương trình NumPy để tìm một ma trận hoặc chỉ tiêu vectơ.**

**Write a NumPy program to find a matrix or vector norm.**



In [12]:
v = np.arange(7)
result = np.linalg.norm(v)
print("Vector norm:")
print(result)
m = np.matrix('1, 2; 3, 4') 
result1 = np.linalg.norm(m)
print("Matrix norm:")
print(result1)

Vector norm:
9.539392014169456
Matrix norm:
5.477225575051661


**11, Viết chương trình NumPy để tính toán định thức của một mảng.**

**Write a NumPy program to compute the determinant of an array.**

![alt text](https://www.w3resource.com/w3r_images/linear-algebra-image-exercise-4.png)



In [13]:
a = np.array([[1,2],[3,4]])
print("Original array:")
print(a)
result =  np.linalg.det(a)
print("Determinant of the said array:")
print(result)

Original array:
[[1 2]
 [3 4]]
Determinant of the said array:
-2.0000000000000004


**12, Viết chương trình NumPy để tính toán nghịch đảo của một ma trận đã cho.**

**Write a NumPy program to compute the inverse of a given matrix.**



In [14]:
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.inv(m)
print("Inverse of the said matrix:")
print(result)

Original matrix:
[[1 2]
 [3 4]]
Inverse of the said matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


**13, Viết chương trình NumPy để tính toán phân tách QR của một ma trận đã cho.**

**Write a NumPy program to calculate the QR decomposition of a given matrix.**

![alt text](https://www.w3resource.com/w3r_images/linear-algebra-image-exercise-13.png)

In [15]:
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.qr(m)
print("Decomposition of the said matrix:")
print(result)

Original matrix:
[[1 2]
 [3 4]]
Decomposition of the said matrix:
(array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]]), array([[-3.16227766, -4.42718872],
       [ 0.        , -0.63245553]]))


**14, Viết chương trình NumPy để tính số điều kiện của một ma trận đã cho.**

**Write a NumPy program to compute the condition number of a given matrix.**



In [16]:
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.cond(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[1 2]
 [3 4]]
Condition number of the said matrix:
14.933034373659268


**15, Viết chương trình NumPy để tính tổng của phần tử đường chéo của một mảng đã cho.**

**Write a NumPy program to compute the sum of the diagonal element of a given array.**



In [17]:
m = np.arange(6).reshape(2,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]]
Condition number of the said matrix:
4


**16, Viết chương trình NumPy để lấy L hình tam giác thấp hơn trong phân tách Cholesky của một mảng nhất định.**

**Write a NumPy program to get the lower-triangular L in the Cholesky decomposition of a given array.**



In [18]:
a = np.array([[4, 12, -16], [12, 37, -53], [-16, -53, 98]], dtype=np.int32)
print("Original array:")
print(a)
L = np.linalg.cholesky(a)
print("Lower-trianglular L in the Cholesky decomposition of the said array:")
print(L)

Original array:
[[  4  12 -16]
 [ 12  37 -53]
 [-16 -53  98]]
Lower-trianglular L in the Cholesky decomposition of the said array:
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8. -5.  3.]]


**17, Viết chương trình NumPy để lấy hệ số qr của một mảng đã cho.**

**Write a NumPy program to get the qr factorization of a given array.**



In [19]:
a = np.array([[4, 12, -14], [12, 37, -53], [-14, -53, 98]], dtype=np.int32)
print("Original array:")
print(a)
q, r = np.linalg.qr(a)
print("qr factorization of the said array:")
print( "q=\n", q, "\nr=\n", r)

Original array:
[[  4  12 -14]
 [ 12  37 -53]
 [-14 -53  98]]
qr factorization of the said array:
q=
 [[-0.21199958 -0.27930103  0.93650794]
 [-0.63599873 -0.68815735 -0.34920635]
 [ 0.74199852 -0.66964945 -0.03174603]] 
r=
 [[-18.86796226 -65.4018692  109.39178122]
 [  0.           6.67798664 -25.24309237]
 [  0.           0.           2.28571429]]


**18, Viết chương trình NumPy để tính hệ số của một mảng đã cho bằng cách phân tách giá trị số đơn.**

**Write a NumPy program to compute the factor of a given array by Singular Value Decomposition.**



In [20]:
a = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
print("Original array:")
print(a)
U, s, V = np.linalg.svd(a, full_matrices=False)
q, r = np.linalg.qr(a)
print("Factor of a given array  by Singular Value Decomposition:")
print("U=\n", U, "\ns=\n", s, "\nV=\n", V)

Original array:
[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]
Factor of a given array  by Singular Value Decomposition:
U=
 [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] 
s=
 [3.       2.236068 2.       0.      ] 
V=
 [[-0.         0.         1.        -0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [-0.         1.         0.        -0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]]


**19, Viết chương trình NumPy để tính định mức Frobenius và số điều kiện của một mảng đã cho.**

In [21]:
a = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(a)
print("Frobenius norm and the condition number:")
print(np.linalg.norm(a, 'fro'))
print(np.linalg.cond(a, 'fro'))

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Frobenius norm and the condition number:
16.881943016134134
inf
