<a href="https://colab.research.google.com/github/bimbeo/Web/blob/master/NumPy_Array_Object_1_100.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://www.w3resource.com/w3r_images/python-numpy-arrays-image.png)

**1, Viết chương trình NumPy để in phiên bản NumPy trong hệ thống của bạn.**

Write a NumPy program to print the NumPy version in your system. ![alt text](https://)



In [2]:
import numpy as np
print(np.__version__)

1.18.4


**2, Viết chương trình NumPy để chuyển đổi danh sách giá trị số thành mảng NumPy một chiều.**

**Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.**

**numpy.array(object, dtype=None, copy=True, order=’K’, subok=False, ndmin=0)**

object ->	An array, any object exposing the array interface.

dtype : data-type, optional ->	The desired data-type for the array.

copy (bool) ->	If true (default), then the object is copied.

order : 'K', 'A', 'C', 'F' ->	Specify the memory layout of the array. If object is not an array, the newly created array will be in C order (row major) unless ‘F’ is specified, in which case it will be in Fortran order.

subok (bool) ->	If True, then sub-classes will be passed-through, otherwise the returned array will be forced to be a base-class array.

ndmin (int) ->	Specifies the minimum number of dimensions that the resulting array should have.

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-2.png)

In [0]:
l = [12.23, 13.32, 100, 36.32]
print("Original List: ", l)
a = np.array(l)
print("One-dimensional Numpy array: ", a)

Original List:  [12.23, 13.32, 100, 36.32]
One-dimensional Numpy array:  [ 12.23  13.32 100.    36.32]


**3, Viết chương trình NumPy để tạo ma trận 3x3 với các giá trị nằm trong khoảng từ 2 đến 10..**

**Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-3.png)

In [0]:
x = np.arange(2, 11).reshape(3, 3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


**4, Viết chương trình NumPy để tạo một vectơ null có kích thước 10 và cập nhật giá trị thứ sáu thành 11.**

**Write a NumPy program to create a null vector of size 10 and update sixth value to 11.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-4.png)

In [0]:
x = np.zeros(10)
print(x)
print("Update sixth value to 11: ")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11: 
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


**5, Viết chương trình NumPy để tạo một mảng với các giá trị nằm trong khoảng từ 12 đến 38.**

**Write a NumPy program to create an array with values ranging from 12 to 38.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-5.png)

In [0]:
x = np.arange(12, 38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


**6, Viết chương trình NumPy để đảo ngược một mảng (phần tử đầu tiên trở thành cuối cùng).**

**Write a NumPy program to reverse an array (first element becomes last).**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-6.png)

In [0]:
x = np.arange(12, 38)
print("Original array: ")
print(x)
print("Reversed array: ")
x = x[::-1]
print(x)

Original array: 
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reversed array: 
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


**7, Viết chương trình NumPy để chuyển đổi một mảng thành kiểu float.**

**Write a NumPy program to convert an array to a float type.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-7.png)

In [0]:
a = [1, 2, 3, 4]
print("Original array: ")
print(a)
x = np.asfarray(a)
print("Array converted to a float type: ")
print(x)

Original array: 
[1, 2, 3, 4]
Array converted to a float type: 
[1. 2. 3. 4.]


**8, Viết chương trình NumPy để tạo mảng 2d với 1 trên đường viền và 0 bên trong.**

**Write a NumPy program to create a 2d array with 1 on the border and 0 inside.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-8.png)

In [0]:
x = np.ones((5,5))
print("Original array: ")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1, 1:-1] = 0
print(x)

Original array: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**9, Viết chương trình NumPy để thêm đường viền (được điền 0) xung quanh một mảng hiện có.**

**Write a NumPy program to add a border (filled with 0's) around an existing array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-9.png)

In [0]:
x = np.ones((3,3))
print("Original array: ")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width = 1, mode = 'constant', constant_values = 0)
print(x)

Original array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**10, Viết chương trình NumPy để tạo ma trận 8x8 và điền nó với mẫu hình bàn cờ.**

**Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.**



In [0]:
x = np.ones((3,3))
print("Checkerboard pattern: ")
x = np.zeros((8,8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

Checkerboard pattern: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**11, Viết chương trình NumPy để chuyển đổi danh sách và tuple thành mảng.**

**Write a NumPy program to convert a list and tuple into arrays.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-11.png)

In [0]:
my_list = [1,2,3,4,5,6,7,8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 4, 6], [1,2,3])
print("Tuple to array: ")
print(np.asarray(my_tuple))

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


**12, Viết chương trình NumPy để nối các giá trị vào cuối một mảng.**

**Write a NumPy program to append values to the end of an array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-12.png)

In [4]:
x = [10, 20, 30]
print("Original array: ")
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array: ")
print(x)


Original array: 
[10, 20, 30]
After append values to the end of the array: 
[10 20 30 40 50 60 70 80 90]


**13, Viết chương trình NumPy để tạo một mảng trống và đầy đủ.**

**Write a NumPy program to create an empty and a full array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-13.png)

In [6]:
x = np.empty((3,4))
print(x)
y = np.full((3,3), 6)
print(y)

[[3.05865528e-316 0.00000000e+000 4.11556683e-321 1.97082588e-316]
 [6.94420914e-310 6.94420914e-310 6.94420914e-310 6.94420914e-310]
 [0.00000000e+000 1.03753786e-322 6.36598737e-314 0.00000000e+000]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


**14, Viết chương trình NumPy để chuyển đổi các giá trị độ C thành độ Fahrenheit. Giá trị C. được lưu trữ trong một mảng NumPy.**

**Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-14.png)

In [0]:
fvalues = [0,12,45.21,34,99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees: ")
print(F)
print("Values in Centigrade degrees: ")
print(5*F/9 - 5*32/9)

Values in Fahrenheit degrees: 
[ 0.   12.   45.21 34.   99.91]
Values in Centigrade degrees: 
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


**15, Viết chương trình NumPy để tìm phần thực và phần ảo của một mảng các số phức**

**Write a NumPy program to find the real and imaginary parts of an array of complex numbers**



In [0]:
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
print("Original array:x ",x)
print("Original array:y ",y)
print("Real part of the array:")
print(x.real)
print(y.real)
print("Imaginary part of the array: ")
print(x.imag)
print(y.imag)

Original array:x  [1.+0.j]
Original array:y  [0.70710678+0.70710678j]
Real part of the array:
[1.]
[0.70710678]
Imaginary part of the array: 
[0.]
[0.70710678]


**16, Viết chương trình NumPy để tìm số phần tử của một mảng, độ dài của một phần tử mảng tính bằng byte và tổng số byte được tiêu thụ bởi các phần tử**

**Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-16.png)

In [0]:
x = np.array([1,2,3, 4], dtype=np.float64)
print("Size of the arary: ", x.size)
print("Length of one array elenment in bytes: ", x.itemsize)
print("Total bytes consumed by the elements of the array: ", x.nbytes)

Size of the arary:  4
Length of one array elenment in bytes:  8
Total bytes consumed by the elements of the array:  32


**17, Viết chương trình NumPy để kiểm tra xem mỗi phần tử của mảng 1-D cũng có trong mảng thứ hai hay không.**

**Write a NumPy program to test whether each element of a 1-D array is also present in a second array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-17.png)


In [0]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ", array1)
array2 = [0, 40]
print("Array2: ", array2)
print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [0, 40]
Compare each element of array1 and array2
[ True False False  True False]


**18, Viết chương trình NumPy để tìm các giá trị chung giữa hai mảng.**

**Write a NumPy program to find common values between two arrays.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-18.png)

In [0]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ", array1)
array2 = [10, 30, 40]
print("Array2: ", array2)
print("Common values between two array: ")
print(np.intersect1d(array1, array2))           # phần giao

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two array: 
[10 40]


**19, Viết chương trình NumPy để lấy các phần tử duy nhất của một mảng.**

**Write a NumPy program to get the unique elements of an array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-19.png)


In [0]:
x = np.array([10, 10, 20, 20, 30, 30])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))
x = np.array([[1, 1], [2, 3]])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


**20, Viết chương trình NumPy để tìm sự khác biệt thiết lập của hai mảng. Sự khác biệt được thiết lập sẽ trả về các giá trị duy nhất được sắp xếp trong mảng1 không nằm trong mảng2.**

**Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.**

np.setdiff1d(array1, array2):

Find the set difference of two arrays.

Return the unique values in ar1 that are not in ar2.

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-20.png)

In [0]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values in array1 that are not in array2:
[ 0 20 60 80]


**21, Viết chương trình NumPy để tìm tập hợp độc quyền - hoặc của hai mảng. Đặt độc quyền - hoặc sẽ trả về các giá trị duy nhất được sắp xếp chỉ trong một (không phải cả hai) của mảng đầu vào**

**Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.**

np.setxor1d(array1, array2)

Find the set exclusive-or of two arrays.

Return the sorted, unique values that are in only one (not both) of the input arrays.

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-21.png)

In [0]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


**22, Viết chương trình NumPy để tìm liên kết của hai mảng. Union sẽ trả về mảng giá trị duy nhất, được sắp xếp nằm trong một trong hai mảng đầu vào.**

**Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.**

np.union1d(array1, array2)

Find the union of two arrays.

Return the unique, sorted array of values that are in either of the two input arrays.
![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-22.png)

In [0]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique sorted array of values that are in either of the two input arrays:")
print(np.union1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique sorted array of values that are in either of the two input arrays:
[ 0 10 20 30 40 50 60 70 80]


**23, Viết chương trình NumPy để kiểm tra xem tất cả các phần tử trong một mảng có đánh giá là True hay không.**

**Write a NumPy program to test whether all elements in an array evaluate to True.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-23.png)

In [0]:
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


**24, Viết chương trình NumPy để kiểm tra xem bất kỳ phần tử mảng nào dọc theo trục đã cho có đánh giá là True hay không.**

**Write a NumPy program to test whether any array element along a given axis evaluates to True.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-24.png)

In [0]:
print(np.any([[False,False],[False,False]]))
print(np.any([[True,True],[True,True]]))
print(np.any([10, 20, 0, -50]))
print(np.any([10, 20, -50]))

False
True
True
True


**25, Viết chương trình NumPy để xây dựng một mảng bằng cách lặp lại.**

**Write a NumPy program to construct an array by repeating.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-25.png)


In [0]:
a = [1, 2, 3, 4]
print("Original array")
print(a)
print("Repeating 2 times")
x = np.tile(a, 2)
print(x)
print("Repeating 3 times")
x = np.tile(a, 3)
print(x)


Original array
[1, 2, 3, 4]
Repeating 2 times
[1 2 3 4 1 2 3 4]
Repeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]


**26, Viết chương trình NumPy để lặp lại các phần tử của một mảng.**

**Write a NumPy program to repeat elements of an array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-26.png)

In [7]:
x = np.repeat(3,4)
print(x)
x = np.array([[1,2], [3,4]])
print(np.repeat(x, 2))
print(np.tile(x, 2))

[3 3 3 3]
[1 1 2 2 3 3 4 4]
[[1 2 1 2]
 [3 4 3 4]]


**27, Viết chương trình NumPy để tìm các chỉ số của các giá trị tối đa và tối thiểu dọc theo trục đã cho của một mảng.**

**Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-27.png)

In [0]:
x = np.array([1, 2, 3, 4, 5, 6])
print("Original array: ",x)
print("Maximum Values: ",np.argmax(x))
print("Minimum Values: ",np.argmin(x))

Original array:  [1 2 3 4 5 6]
Maximum Values:  5
Minimum Values:  0


**28, Viết chương trình NumPy so sánh hai mảng đã cho.**

**Write a NumPy program compare two given arrays.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-28.png)

In [0]:
a = np.array([1, 2])
b = np.array([4, 5])
print("Array a: ",a)
print("Array b: ",b)
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))

Array a:  [1 2]
Array b:  [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


**29, Viết chương trình NumPy để sắp xếp một trục dọc đầu tiên, cuối cùng của một mảng.**

**Write a NumPy program to sort an along the first, last axis of an array.**


In [0]:
a = np.array([[4, 6],[2, 1]])
print("Original array: ")
print(a)
print("Sort along the first axis: ")
x = np.sort(a, axis=0)
print(x)
print("Sort along the last axis: ")
y = np.sort(x, axis=1)
print(y)

Original array: 
[[4 6]
 [2 1]]
Sort along the first axis: 
[[2 1]
 [4 6]]
Sort along the last axis: 
[[1 2]
 [4 6]]


**30, Viết chương trình NumPy để sắp xếp các cặp tên và họ trả về các chỉ số của chúng. (đầu tiên bằng tên cuối cùng, sau đó bằng tên đầu tiên).**

**Write a NumPy program to sort pairs of first name and last name return their indices. (first by last name, then by first name).**


In [0]:
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)

[1 3 2 4 0]


**31, Viết chương trình NumPy để lấy các giá trị và chỉ số của các phần tử lớn hơn 10 trong một mảng nhất định.**

**Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-31.png)

In [0]:
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


**32, Viết chương trình NumPy để lưu mảng NumPy vào tệp văn bản.**

**Write a NumPy program to save a NumPy array to a text file.**



In [0]:
a = np.arange(1.0, 2.0, 36.2)
np.savetxt('file.out', a, delimiter=',')

**33, Viết chương trình NumPy để tìm kích thước bộ nhớ của mảng NumPy.**

**Write a NumPy program to find the memory size of a NumPy array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-33.png)

In [0]:
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


**34, Viết chương trình NumPy để tạo một mảng các số và một mảng số không.**

**Write a NumPy program to create an array of ones and an array of zeros.**



In [0]:
print("Create an array of zeros")
x = np.zeros((1,2))
print("Default type is float")
print(x)
print("Type changes to int")
x = np.zeros((1,2), dtype = np.int)
print(x)
print("Create an array of ones")
y= np.ones((1,2)) 
print("Default type is float")
print(y)
print("Type changes to int")
y = np.ones((1,2), dtype = np.int)
print(y)

Create an array of zeros
Default type is float
[[0. 0.]]
Type changes to int
[[0 0]]
Create an array of ones
Default type is float
[[1. 1.]]
Type changes to int
[[1 1]]


**35, Viết chương trình NumPy để thay đổi kích thước của một mảng.**

**Write a NumPy program to change the dimension of an array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-35.png)

In [0]:
x = np.array([1, 2, 3, 4, 5, 6])
print("6 rows and 0 columns")
print(x.shape)

y = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print("(3, 3) -> 3 rows and 3 columns ")
print(y)

x = np.array([1,2,3,4,5,6,7,8,9])
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
x.shape = (3, 3)
print(x)

6 rows and 0 columns
(6,)
(3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**36, Viết chương trình NumPy để tạo một mảng phẳng liền kề.**

**Write a NumPy program to create a contiguous flattened array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-36.png)

In [8]:
x = np.array([[10, 20, 30], [20, 40, 50]])
print("Original array:")
print(x)
y = np.ravel(x)
print("New flattened array: ")
print(y)

Original array:
[[10 20 30]
 [20 40 50]]
New flattened array: 
[10 20 30 20 40 50]


**37, Viết chương trình NumPy để tạo mảng 2 chiều có kích thước 2 x 3 (bao gồm các phần tử nguyên 4 byte), cũng in hình dạng, loại và kiểu dữ liệu của mảng.**

**Write a NumPy program to create a 2-dimensional array of size 2 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-37.png)



In [9]:
x = np.array([[2,4,6], [6,8,10]], np.int32)
print(type(x))
print(x.shape)
print(x.dtype)

<class 'numpy.ndarray'>
(2, 3)
int32


**38, Viết chương trình NumPy để tạo một hình dạng mới cho một mảng mà không thay đổi dữ liệu của nó.**

**Write a NumPy program to create a new shape to an array without changing its data.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-38.png)

In [11]:
x = np.array([1,2,3,4,5,6])
print(x)
y = np.reshape(x, (3,2))
print("Reshape 3x2: ")
print(y)
z = np.reshape(x, (2,3))
print("Reshape 2x3: ")
print(z)

[1 2 3 4 5 6]
Reshape 3x2: 
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3: 
[[1 2 3]
 [4 5 6]]


**39, Viết chương trình NumPy để thay đổi kiểu dữ liệu của một mảng.**

**Write a NumPy program to change the data type of an array.**



In [12]:
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
print("Data type of the array x is: ", x.dtype)
y = x.astype(float)
print("New Type: ", y.dtype)
print(y)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is:  int32
New Type:  float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


 **40, Viết chương trình NumPy để tạo một mảng mới 3 * 5, chứa đầy 2**

 **Write a NumPy program to create a new array of 3*5, filled with 2.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-40.png)

In [14]:
x = np.full((3,5), 2, dtype=np.uint)
print(x)
y = np.ones([3,5], dtype = np.uint) * 2
print(y)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


**41, Viết chương trình NumPy để tạo một mảng 10 giây với cùng hình dạng và kiểu của một mảng nhất định.**

**Write a NumPy program to create an array of 10's with the same shape and type of a given array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-41.png)


In [15]:
x = np.arange(4, dtype=np.int64)
y = np.full_like(x, 10)
print(y)

[10 10 10 10]


**42, Viết chương trình NumPy để tạo một mảng 3 chiều với các mảng trên đường chéo và các số 0 ở nơi khác.**

**Write a NumPy program to create a 3-D array with ones on the diagonal and zeros elsewhere.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-42.png)

In [18]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**43, Viết chương trình NumPy để tạo mảng 2 chiều có đường chéo bằng [4, 5, 6, 8] và 0 ở nơi khác.**

**Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-43.png)

In [20]:
x = np.diagflat([4,5,6,8])
print(x)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


**44, Viết chương trình NumPy để tạo mảng 1-D đi từ 0 đến 50 và mảng từ 10 đến 50.**

**Write a NumPy program to create a 1-D array going from 0 to 50 and an array from 10 to 50.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-44.png)

In [21]:
x = np.arange(50)
print("Array from 0 to 50: ")
print(x)
x = np.arange(10, 50)
print("Array from 10 to 50: ")
print(x)

Array from 0 to 50: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
Array from 10 to 50: 
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**45, Viết chương trình NumPy để tạo mảng 1-D gồm 30 phần tử cách đều nhau giữa 2,5. và 6,5, bao gồm.**

**Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive.**



In [22]:
x = np.linspace(2.5, 6.5, 30)
print(x)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


**46, Viết chương trình NumPy để tạo mảng 1-D gồm 20 phần tử cách đều nhau trên thang đo log giữa 2. và 5., độc quyền.**

**Write a NumPy program to create a 1-D array of 20 element spaced evenly on a log scale between 2. and 5., exclusive.**



In [24]:
x = np.logspace(2., 5., 20, endpoint=False)
print(x)

[  100.           141.25375446   199.5262315    281.83829313
   398.10717055   562.34132519   794.32823472  1122.0184543
  1584.89319246  2238.72113857  3162.27766017  4466.83592151
  6309.5734448   8912.50938134 12589.25411794 17782.79410039
 25118.8643151  35481.33892336 50118.72336273 70794.57843841]


**47, Viết chương trình NumPy để tạo một mảng trông giống như mảng bên dưới.**

**Write a NumPy program to create an array which looks like below array.**



In [25]:
x = np.tri(4, 3, -1)
print(x)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


**48, Viết chương trình NumPy để tạo một mảng trông giống như mảng bên dưới.**

**Write a NumPy program to create an array which looks like below array.**



In [27]:
x = np.triu(np.arange(2, 14).reshape(4,3), -1)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 0  9 10]
 [ 0  0 13]]


**49, Viết chương trình NumPy để thu gọn mảng 3 chiều thành mảng một chiều.**

**Write a NumPy program to collapse a 3-D array into one dimension array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-49.png)

In [28]:
x = np.eye(3)
print("3-D array: ")
print(x)
f = np.ravel(x, order='F')
print("One dimension array: ")
print(f)

3-D array: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
One dimension array: 
[1. 0. 0. 0. 1. 0. 0. 0. 1.]


**50, Viết chương trình NumPy để tìm phần tử thứ 4 của một mảng được chỉ định.**

**Write a NumPy program to find the 4th element of a specified array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-50.png)

In [29]:
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
e1 = x.flat[3]
print("Forth element of the array: ")
print(e1)

[[ 2  4  6]
 [ 6  8 10]]
Forth element of the array: 
6


**51, Viết chương trình NumPy để trao đổi hai trục của một mảng.**

**Write a NumPy program to interchange two axes of an array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-51.png)

In [30]:
x = np.array([[1,2,3]])
print(x)
y = np.swapaxes(x, 0, 1)
print(y)

[[1 2 3]]
[[1]
 [2]
 [3]]


**52, Viết chương trình NumPy để di chuyển các trục của một mảng sang các vị trí mới. Các trục khác vẫn theo thứ tự ban đầu của họ.**

**Write a NumPy program to move axes of an array to new positions. Other axes remain in their original order.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-52.png)

In [31]:
x = np.zeros((2,3,4))
print(np.moveaxis(x, 0, -1). shape)
print(np.moveaxis(x, -1, 0).shape)

(3, 4, 2)
(4, 2, 3)


 **53, Viết chương trình NumPy để di chuyển trục đã chỉ định về phía sau, cho đến khi nó nằm ở một vị trí nhất định.
Di chuyển các trục mảng thứ 3 sau đến vị trí đầu tiên.
(2,3,4,5)**

**Write a NumPy program to move the specified axis backwards, until it lies in a given position.
Move the following 3rd array axes to first position.
(2,3,4,5)**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-53.png)

In [32]:
x = np.ones((2,3,4,5))
print(np.rollaxis(x, 3, 1).shape)

(2, 5, 3, 4)


**54, Viết một chương trình NumPy để chuyển đổi đầu vào quy định để mảng với ít nhất một chiều**

**Write a NumPy program to convert specified inputs to arrays with at least one dimension.**



In [33]:
x = 12.0
print(np.atleast_1d(x))
x = np.arange(6.0).reshape(2, 3)
print(np.atleast_1d(x))
print(np.atleast_1d([1, [3,4]]))

[12.]
[[0. 1. 2.]
 [3. 4. 5.]]
[1 list([3, 4])]


**55, Viết chương trình NumPy để xem các đầu vào dưới dạng các mảng có ít nhất hai chiều, ba chiều.**

**Write a NumPy program to view inputs as arrays with at least two dimensions, three dimensions.**



In [34]:
x = 10
print("View inputs as arrays with at least two dimensions: ")
print(np.atleast_1d(x))
x = np.arange(4.0).reshape(2, 2)
print(np.atleast_1d(x))
print("View inputs as arrays with at least three dimensions: ")
x = 15
print(np.atleast_3d(x))
x = np.arange(3.0)
print(np.atleast_3d(x))

View inputs as arrays with at least two dimensions: 
[10]
[[0. 1.]
 [2. 3.]]
View inputs as arrays with at least three dimensions: 
[[[15]]]
[[[0.]
  [1.]
  [2.]]]


**56, Viết chương trình NumPy để chèn một trục mới trong mảng 2 chiều.
Mảng 2 chiều có hình dạng (3, 4).
Hình dạng mới sẽ là (3, 1, 4).** 

**Write a NumPy program to insert a new axis within a 2-D array.
2-D array of shape (3, 4).
New shape will be will be (3, 1, 4).**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-56.png)

In [35]:
x = np.zeros((3, 4))
y = np.expand_dims(x, axis = 1).shape
print(y)

(3, 1, 4)


**57, Viết chương trình NumPy để xóa các mục một chiều khỏi hình dạng đã chỉ định.**

**Write a NumPy program to remove single-dimensional entries from a specified shape.**


In [36]:
x = np.zeros((3, 1, 4))
print(np.squeeze(x).shape)

(3, 4)


**58, Viết chương trình NumPy để ghép hai mảng 2 chiều.**

**Write a NumPy program to concatenate two 2-dimensional arrays.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-58.png)


In [39]:
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])
c = np.concatenate((a,b), 1)
print(c)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


**59, Viết chương trình NumPy để chuyển đổi mảng 1-D dưới dạng cột thành mảng 2-D.**

**Write a NumPy program to convert 1-D arrays as columns into a 2-D array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-59.png)


In [40]:
a = np.array((10,20,30))
b = np.array((40,50,60))
c = np.column_stack((a, b))
print(c)

[[10 40]
 [20 50]
 [30 60]]


**60, Viết chương trình NumPy để chuyển đổi (theo chiều sâu trình tự (dọc theo trục thứ ba)) hai mảng 1-D thành mảng 2-D.**

**Write a NumPy program to convert (in sequence depth wise (along third axis)) two 1-D arrays into a 2-D array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-60.png)

In [41]:
a = np.array([[10],[20],[30]])
b = np.array([[40],[50],[60]])
c = np.dstack((a,b))
print(c)

[[[10 40]]

 [[20 50]]

 [[30 60]]]


**61, Viết chương trình Python để chia một mảng gồm 14 phần tử thành 3 mảng, mỗi phần có 2, 4 và 8 phần tử theo thứ tự ban đầu.**

**Write a Python program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-61.png)

In [42]:
x = np.arange(1, 15)
print("Original array:",x)
print("After splitting:")
print(np.split(x, [2, 6]))

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After splitting:
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


**62, Viết chương trình NumPy để phân chia một mảng có hình dạng 4 x 4 thành hai mảng dọc theo trục thứ hai.**

**Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-62.png)

In [44]:
x = np.arange(16).reshape((4, 4))
print("Original array:")
print(x)
print("After splitting horizontally:")
print(np.hsplit(x, [2,6]))

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int64)]


**63, Viết chương trình NumPy để lấy số phần tử khác không trong một mảng.**

**Write a NumPy program to get the number of nonzero elements in an array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-63.png)

In [45]:
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array:")
print(x)
print("Number of non zero elements in the above array:")
print(np.count_nonzero(x))

Original array:
[[ 0 10 20]
 [20 30 40]]
Number of non zero elements in the above array:
5


**64, Viết chương trình NumPy để tạo ma trận 5x5 với các giá trị hàng nằm trong khoảng từ 0 đến 4.**

**Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-64.png)

In [46]:
x = np.zeros((5,5))
print("Original array:")
print(x)
print("Row values ranging from 0 to 4.")
x += np.arange(5)
print(x)

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**65, Viết chương trình NumPy để kiểm tra xem các giá trị được chỉ định có trong một mảng hay không.**

**Write a NumPy program to test whether specified values are present in an array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-65.png)

In [47]:
x = np.array([[1.12, 2.0, 3.45], [2.33, 5.12, 6.0]], float) 
print("Original array:")
print(x)
print(2 in x)
print(0 in x)
print(6 in x)
print(2.3 in x)
print(5.12 in x)

Original array:
[[1.12 2.   3.45]
 [2.33 5.12 6.  ]]
True
False
True
False
True


**66, Viết chương trình NumPy để tạo một vectơ kích thước 10 với các giá trị nằm trong khoảng từ 0 đến 1, cả hai đều bị loại trừ.**

**Write a NumPy program to create a vector of size 10 with values ranging from 0 to 1, both excluded.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-66.png)

In [48]:
x = np.linspace(0,1,12, endpoint=True)[1:-1]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**67, Viết chương trình NumPy để tạo một mảng bất biến (chỉ đọc).**

**Write a NumPy program to make an array immutable (read-only).**



In [49]:
x = np.zeros(10)
x.flags.writeable = False
print("Test the array is read-only or not:")
print("Try to change the value of the first element:")
x[0] = 1

Test the array is read-only or not:
Try to change the value of the first element:


ValueError: ignored

**68, Viết chương trình NumPy (sử dụng numpy) để tổng tất cả các bội số của 3 hoặc 5 dưới 100.**

**Write a NumPy program (using numpy) to sum of all the multiples of 3 or 5 below 100.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-68.png)

In [50]:
x = np.arange(1, 100)
n = x[(x % 3 == 0) | (x % 5 == 0) ]
print(n[:1000])
print(n.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


**69, Viết chương trình NumPy để tạo một mảng có 10 ^ 3 phần tử.**

**Write a NumPy program to create an array with 10^3 elements.**



In [51]:
x = np.arange(1e3)
print(x)

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.
  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.
  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.
  98.  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111.
 112. 113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125.
 126. 127. 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139.
 140. 141. 142. 143. 144. 145. 146. 147. 148. 149. 150. 151. 152. 153.
 154. 155. 156. 157. 158. 159. 160. 161. 162. 163. 164. 165. 166. 167.
 168. 169. 170. 171. 172. 173. 174. 175. 176. 177. 178. 179. 180. 181.
 182. 183. 184. 185. 186. 187. 188. 189. 190. 191. 192. 193. 194. 195.
 196. 

**70, Viết chương trình NumPy để tạo và hiển thị mọi phần tử của mảng numpy.**

**Write a NumPy program to create and display every element of a numpy array.**



In [54]:
x = np.arange(12).reshape(3, 4)
for x in np.nditer(x):
  print(x, end=' ')
print()

0 1 2 3 4 5 6 7 8 9 10 11 


**71, Viết chương trình NumPy để tạo và hiển thị mọi phần tử của một mảng numpy theo thứ tự Fortran.**

**Write a NumPy program to create and display every element of a numpy array in Fortran order.**



In [55]:
x = np.arange(12).reshape(3, 4)
print("Elements of the array in Fortan array: ")
for x in np.nditer(x, order="F"):
  print(x, end=' ')
print("\n")

Elements of the array in Fortan array: 
0 4 8 1 5 9 2 6 10 3 7 11 



**72, Viết chương trình NumPy để tạo khối 5x5x5 bằng 1.**

**Write a NumPy program to create a 5x5x5 cube of 1's.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-72.png)

In [56]:
x = np.zeros((5, 5, 5)).astype(int) + 1
print(x)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


**73, Viết chương trình NumPy để tạo một mảng có hình dạng (3, 4), nhân mọi giá trị phần tử với 3 và hiển thị mảng mới.**

**Write a NumPy program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-73.png)

In [57]:
x = np.arange(12).reshape(3, 4)
print("Original array elements: ")
print(x)
for a in np.nditer(x, op_flags=['readwrite']):
  a[...] = 3 * a
print("New array elements: ")
print(x)

Original array elements: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array elements: 
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


**74, Viết chương trình NumPy để kết hợp một mảng một và hai chiều với nhau và hiển thị các phần tử của chúng.**

**Write a NumPy program to combine a one and a two dimensional array together and display their elements.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-74.png)

In [58]:
x = np.arange(4)
print("One dimensional array: ")
print(x)
y = np.arange(8).reshape(2,4)
print("Two dimensional array: ")
print(y)
for a, b in np.nditer([x, y]):
  print("%d : %d" % (a,b))

One dimensional array: 
[0 1 2 3]
Two dimensional array: 
[[0 1 2 3]
 [4 5 6 7]]
0 : 0
1 : 1
2 : 2
3 : 3
0 : 4
1 : 5
2 : 6
3 : 7


**75, Viết chương trình NumPy để tạo một mảng các số không và ba loại cột (số nguyên, số float, ký tự).**

**Write a NumPy program to create an array of zeros and three column types (integer, float, character).**


In [59]:
x = np.zeros((3,), dtype=('i4,f4, a40'))
new_data = [(1, 2., "Albert Einstein"), (2, 2., "Edmond Halley"), (3, 3., "Gertrude B. Elion")]
x[:] = new_data
print(x)

[(1, 2., b'Albert Einstein') (2, 2., b'Edmond Halley')
 (3, 3., b'Gertrude B. Elion')]


**76, Viết chương trình NumPy để tạo một khối chức năng, tạo ra tất cả các phần tử của một mảng.**

**Write a NumPy program to create a function cube which cubes all the elements of an array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-76.png)

In [60]:
def cube(e):
  it = np.nditer([e, None])
  for a, b in it:
    b[...] = a*a*a
  return it.operands[1]
print(cube([1, 2, 3]))

[ 1  8 27]


**77, Viết chương trình NumPy để tạo một mảng có hình dạng (3, 4) và chuyển đổi các phần tử mảng thành các phần nhỏ hơn.**

**Write a NumPy program to create an array of (3, 4) shape and convert the array elements in smaller chunks.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-77.png)

In [61]:
x= np.arange(12).reshape(3, 4)
print("Original array elements:")
print(x)
print("Above array in small chuncks:")
for a in np.nditer(x, flags=['external_loop'], order='F'):
  print(a)

Original array elements:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Above array in small chuncks:
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


**78, Viết chương trình NumPy để tạo một mảng bản ghi từ danh sách các mảng (phẳng).**

**Write a NumPy program to create a record array from a (flat) list of arrays.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-78.png)

In [62]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result = np.core.records.fromarrays([a1, a2, a3], names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)


**79, Viết chương trình NumPy để tạo một mảng giống như Gaussian 2D.**

**Write a NumPy program to generate a generic 2D Gaussian-like array.**



In [64]:
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
g = np.exp(- (d-mu)**2 / (2.0 *sigma **2))
print("2D Gaussian-like array:")
print(g)

2D Gaussian-like array:
[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0

**80, Viết chương trình NumPy để chuyển đổi một mảng NumPy thành cấu trúc danh sách Python.**

**Write a NumPy program to convert a NumPy array into Python list structure.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-80.png)

In [65]:
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


**81, Viết chương trình NumPy để truy cập một mảng theo cột.**

**Write a NumPy program to access an array by column.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-81.png)

In [66]:
x= np.arange(9).reshape(3,3)
print("Original array elements:")
print(x)
print("Access an array by column:")
print("First column:")
print(x[:,0])
print("Second column: ")
print(x[:, 1])
print("Third column: ")
print(x[:, 2])

Original array elements:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Access an array by column:
First column:
[0 3 6]
Second column: 
[1 4 7]
Third column: 
[2 5 8]


**82, Viết chương trình NumPy để chuyển đổi một mảng NumPy của các giá trị float thành một mảng NumPy của các giá trị nguyên.**

**Write a NumPy program to convert a NumPy array of float values to a NumPy array of integer values**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-82.png)

In [67]:
x= np.array([[12.0, 12.51], [2.34, 7.98], [25.23, 36.50]])
print("Original array elements:")
print(x)
print("Convert float values to integer values:")
print(x.astype(int))

Original array elements:
[[12.   12.51]
 [ 2.34  7.98]
 [25.23 36.5 ]]
Convert float values to integer values:
[[12 12]
 [ 2  7]
 [25 36]]


**83, Viết chương trình NumPy để hiển thị các phần tử mảng NumPy của các giá trị nổi với độ chính xác đã cho.**

**Write a NumPy program to display NumPy array elements of floating values with given precision.**



In [68]:
x=np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,             
  0.35399976, 0.99469633, 0.0694458, 0.54711478]) 
print("Original array elements:")
print(x)
print("Print array values with precision 3:")
np.set_printoptions(precision=3)
print(x)

Original array elements:
[0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]
Print array values with precision 3:
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


**84, Viết chương trình NumPy để loại bỏ việc sử dụng ký hiệu khoa học cho các số nhỏ trong mảng NumPy.**

**Write a NumPy program to suppresses the use of scientific notation for small numbers in NumPy array.**



In [69]:
x=np.array([1.6e-10, 1.6, 1200, .235]) 
print("Original array elements:")
print(x)
print("Print array values with precision 3:")
np.set_printoptions(suppress=True)
print(x)

Original array elements:
[1.60e-10 1.60e+00 1.20e+03 2.35e-01]
Print array values with precision 3:
[   0.       1.6   1200.       0.235]


**85, Viết chương trình NumPy để tạo một mảng NumPy gồm 10 số nguyên từ một trình tạo.**

**Write a NumPy program to create a NumPy array of 10 integers from a generator.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-85.png)

In [70]:
iterable = (x for x in range(10))
print(np.fromiter(iterable, np.int))

[0 1 2 3 4 5 6 7 8 9]


**86, Viết chương trình NumPy để thêm một cột phụ vào mảng NumPy.**

**Write a NumPy program to add an extra column to a NumPy array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-86.png)

In [71]:
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])
print(np.append(x, y, axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


**87, Viết chương trình NumPy để tìm các hàng duy nhất trong mảng NumPy.**

**Write a NumPy program to find unique rows in a NumPy array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-87.png)

In [73]:
x = np.array([[20, 20, 20, 0],
              [0, 20, 20, 20],
              [0, 20, 20, 20],
              [20, 20, 20, 0],
              [10, 20, 20,20]])
print("Original array:")
print(x)
y = np.ascontiguousarray(x).view(np.dtype((np.void, x.dtype.itemsize * x.shape[1])))
_, idx = np.unique(y, return_index=True)

unique_result = x[idx]
print("Unique rows of the above array: ")
print(unique_result)

Original array:
[[20 20 20  0]
 [ 0 20 20 20]
 [ 0 20 20 20]
 [20 20 20  0]
 [10 20 20 20]]
Unique rows of the above array: 
[[ 0 20 20 20]
 [10 20 20 20]
 [20 20 20  0]]


**88, Viết chương trình NumPy để thay thế tất cả các phần tử của mảng NumPy lớn hơn mảng đã chỉ định.**

**Write a NumPy program to replace all elements of NumPy array that are greater than specified array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-88.png)

In [74]:
x = np.array([[ 0.42436315, 0.48558583, 0.32924763], [ 0.7439979,0.58220701,0.38213418], [ 0.5097581,0.34528799,0.1563123 ]])
print("Original array:")
print(x)
print("Replace all elements of the said array with .5 which are greater than .5")
x[x > .5] = .5
print(x)

Original array:
[[0.424 0.486 0.329]
 [0.744 0.582 0.382]
 [0.51  0.345 0.156]]
Replace all elements of the said array with .5 which are greater than .5
[[0.424 0.486 0.329]
 [0.5   0.5   0.382]
 [0.5   0.345 0.156]]


**89, Viết chương trình NumPy để loại bỏ các phần tử cụ thể trong mảng NumPy.**

**Write a NumPy program to remove specific elements in a NumPy array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-89.png)

In [76]:
x = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
index = [0, 3, 4]
print("Original array:")
print(x)
print("Delete first, fourth and fifth elements:")
new_x = np.delete(x, index)
print(new_x)

Original array:
[ 10  20  30  40  50  60  70  80  90 100]
Delete first, fourth and fifth elements:
[ 20  30  60  70  80  90 100]


**90, Viết chương trình NumPy để loại bỏ các giá trị âm trong mảng NumPy bằng 0.**

**Write a NumPy program to remove the negative values in a NumPy array with 0.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-90.png)

In [77]:
x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])
print("Original array:")
print(x)
print("Replace the negative values of the said array with 0:")
x [x < 0] = 0
print(x)

Original array:
[-1 -4  0  2  3  4  5 -6]
Replace the negative values of the said array with 0:
[0 0 0 2 3 4 5 0]


**91, Viết chương trình NumPy để xóa tất cả các hàng trong mảng NumPy có chứa các giá trị không phải là số.**

**Write a NumPy program to remove all rows in a NumPy array that contain non-numeric values.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-91.png)

In [78]:
x = np.array([[1,2,3], [4,5,np.nan], [7,8,9], [True, False, True]])
print("Original array:")
print(x)
print("Remove all non-numeric elements of the said array")
print(x[~np.isnan(x).any(axis=1)])

Original array:
[[ 1.  2.  3.]
 [ 4.  5. nan]
 [ 7.  8.  9.]
 [ 1.  0.  1.]]
Remove all non-numeric elements of the said array
[[1. 2. 3.]
 [7. 8. 9.]
 [1. 0. 1.]]


**92, Viết chương trình NumPy để chọn các chỉ mục thỏa mãn nhiều điều kiện trong một mảng NumPy.**

**Write a NumPy program to select indices satisfying multiple conditions in a NumPy array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-92.png)

In [79]:
a = np.array([97, 101, 105, 111, 117])
b = np.array(['a','e','i','o','u'])
print("Original arrays")
print(a)
print(b)
print("Elements from the second array  corresponding to elements in the first array  that are greater than 100 and less than 110:")
print(b[(100 < a) & (a < 110)])

Original arrays
[ 97 101 105 111 117]
['a' 'e' 'i' 'o' 'u']
Elements from the second array  corresponding to elements in the first array  that are greater than 100 and less than 110:
['e' 'i']


**93, Viết chương trình NumPy để lấy độ lớn của vectơ trong NumPy.**

**Write a NumPy program to get the magnitude of a vector in NumPy.**



In [80]:
x = np.array([1,2,3,4,5])
print("Original array:")
print(x)
print("Magnitude of the vector:")
print(np.linalg.norm(x))

Original array:
[1 2 3 4 5]
Magnitude of the vector:
7.416198487095663


**94, Viết chương trình NumPy để đếm tần số của các giá trị duy nhất trong mảng numpy.**

**Write a NumPy program to count the frequency of unique values in numpy array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-94.png)

In [81]:
a = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Original array:")
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


**95, Viết chương trình NumPy để kiểm tra xem mảng numpy có trống hay không.**

**Write a NumPy program to check whether the numpy array is empty or not.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-95.png)

In [82]:
x = np.array([2, 3])
y = np.array([])
# size 2, array is not empty
print(x.size)
# size 0, array is empty
print(y.size)

2
0


**96, Viết chương trình NumPy để chia mỗi hàng cho một phần tử vectơ.**

**Write a NumPy program to divide each row by a vector element.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-96.png)

In [83]:
x = np.array([[20,20,20],[30,30,30],[40,40,40]])
print("Original array:")
print(x)
v = np.array([20,30,40])
print("Vector:")
print(v)
print(x / v[:, None])

Original array:
[[20 20 20]
 [30 30 30]
 [40 40 40]]
Vector:
[20 30 40]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**97, Viết chương trình NumPy để in tất cả các giá trị của một mảng.**

**Write a NumPy program to print all the values of an array.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-97.png)

In [0]:
np.set_printoptions(threshold=np.nan)
x = np.zeros((4, 4))
print(x)
"""   Báo lỗi nan:
      [[ 0.  0.  0.  0.]                                                     
      [ 0.  0.  0.  0.]                                                     
      [ 0.  0.  0.  0.]                                                     
      [ 0.  0.  0.  0.]]                                  """

**98, Viết chương trình NumPy để chuyển đổi dữ liệu thô trong một mảng thành chuỗi nhị phân và sau đó tạo một mảng.**

**Write a NumPy program to convert the raw data in an array to a binary string and then create an array.**



In [88]:
x = np.array([10, 20, 30], float)
print("Original array:")
print(x)
s = x.tostring()
print("Binary string array: ")
print(s)
print("Array using fromstring(): ")
y = np.fromstring(s)
print(y)

Original array:
[10. 20. 30.]
Binary string array: 
b'\x00\x00\x00\x00\x00\x00$@\x00\x00\x00\x00\x00\x004@\x00\x00\x00\x00\x00\x00>@'
Array using fromstring(): 
[10. 20. 30.]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  


**99, Viết chương trình NumPy để tính tổng và tính tích của một phần tử mảng NumPy.**

**Write a NumPy program to sum and compute the product of a NumPy array elements.**

![alt text](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-99.png)

In [89]:
x = np.array([10, 20, 30], float)
print("Original array:")
print(x)
print("Sum of the array elements:")
print(x.sum())
print("Product of the array elements: ")
print(x.prod())

Original array:
[10. 20. 30.]
Sum of the array elements:
60.0
Product of the array elements: 
6000.0


**100, Viết chương trình NumPy để lấy các giá trị từ một mảng nguồn và đặt chúng vào các chỉ số được chỉ định của một mảng khác.**

**Write a NumPy program to take values from a source array and put them at specified indices of another array.**





In [90]:
x = np.array([10, 10, 20, 30, 30], float)
print(x)
print("Put 0 and 40 in first and fifth position of the above array")
y = np.array([0, 40, 60], float)
x.put([0, 4], y)
print("Array x, after putting two values: ")
print(x)

[10. 10. 20. 30. 30.]
Put 0 and 40 in first and fifth position of the above array
Array x, after putting two values: 
[ 0. 10. 20. 30. 40.]
