<a href="https://colab.research.google.com/github/bimbeo/Web/blob/master/Random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**1, Viết chương trình NumPy để tạo năm số ngẫu nhiên từ phân phối chuẩn**

**Write a NumPy program to generate five random numbers from the normal distribution.**

![alt text](https://www.w3resource.com/w3r_images/numpy-random-image-exercise-1.svg)




In [1]:
import numpy as np
x = np.random.normal(size=5)
print(x)

[0.53693183 0.0363126  0.83444433 0.45995284 0.22505898]


**2, Viết chương trình NumPy để tạo sáu số nguyên ngẫu nhiên trong khoảng từ 10 đến 30.**

**Write a NumPy program to generate six random integers between 10 and 30.**

![alt text](https://www.w3resource.com/w3r_images/numpy-random-image-exercise-2.svg)


In [3]:
x = np.random.randint(low=10, high=30, size=6)
print(x)

[17 21 16 21 10 26]


**3, Viết chương trình NumPy để tạo mảng 3x3x3 với các giá trị ngẫu nhiên.**

**Write a NumPy program to create a 3x3x3 array with random values.**

![alt text](https://www.w3resource.com/w3r_images/numpy-random-image-exercise-3.svg)

In [4]:
x = np.random.random((3,3,3))
print(x)

[[[0.56653799 0.48777661 0.79389806]
  [0.70281665 0.10570826 0.65011136]
  [0.21959475 0.39626761 0.44472104]]

 [[0.8522426  0.98672524 0.10469457]
  [0.5994622  0.1338635  0.31541017]
  [0.58464647 0.30717534 0.84953033]]

 [[0.96465001 0.87747559 0.25369999]
  [0.75898423 0.94577029 0.47037829]
  [0.9440824  0.11187298 0.77394678]]]


**4, Viết chương trình NumPy để tạo mảng 5x5 với các giá trị ngẫu nhiên và tìm giá trị tối thiểu và tối đa.**

**Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.**

![alt text](https://www.w3resource.com/w3r_images/numpy-random-image-exercise-4.svg)

In [5]:
x = np.random.random((5,5))
print("Original Array: ")
print(x)
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum values:")
print(xmin, xmax)

Original Array: 
[[0.41247534 0.24923478 0.57571421 0.08740884 0.75989577]
 [0.27835029 0.03125174 0.27136207 0.30269471 0.47619743]
 [0.41955956 0.13238293 0.4530602  0.12579379 0.8375538 ]
 [0.11464909 0.497667   0.50780222 0.4363506  0.10879906]
 [0.67916839 0.45055777 0.05656541 0.25618814 0.99876711]]
Minimum and Maximum values:
0.03125173506538326 0.9987671096645896


**5, Viết chương trình NumPy để tạo một mảng 10x4 ngẫu nhiên và trích xuất năm hàng đầu tiên của mảng và lưu trữ chúng thành một biến.**

**Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.**

![alt text](https://www.w3resource.com/w3r_images/numpy-random-image-exercise-5.svg)

In [6]:
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y = x[:5, :]
print("First 5 rows of the above array: ")
print(y)

Original array: 
[[0.02952127 0.3762359  0.6029752  0.4842019 ]
 [0.51188205 0.6638141  0.59405364 0.88016672]
 [0.12966657 0.14608739 0.18052942 0.51616037]
 [0.8005109  0.27677779 0.87720019 0.79776479]
 [0.85958421 0.10274683 0.24229675 0.57229485]
 [0.42579989 0.9004281  0.15481657 0.97792081]
 [0.45935674 0.12289938 0.31012012 0.55694964]
 [0.27783782 0.69769881 0.60791018 0.02262419]
 [0.86971218 0.43646298 0.63350805 0.78271213]
 [0.36878994 0.83488142 0.79386889 0.03248687]]
First 5 rows of the above array: 
[[0.02952127 0.3762359  0.6029752  0.4842019 ]
 [0.51188205 0.6638141  0.59405364 0.88016672]
 [0.12966657 0.14608739 0.18052942 0.51616037]
 [0.8005109  0.27677779 0.87720019 0.79776479]
 [0.85958421 0.10274683 0.24229675 0.57229485]]


**6, Viết chương trình NumPy để xáo trộn các số từ 0 đến 10 (đã bao gồm).**

**Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).**

![alt text](https://www.w3resource.com/w3r_images/numpy-random-image-exercise-6.svg)

In [7]:
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation(): ")
print(np.random.permutation(10))

[6 4 0 7 9 2 8 3 5 1]
Same result using permutation(): 
[1 8 0 7 9 5 3 6 4 2]


**7, Viết chương trình NumPy để chuẩn hóa ma trận ngẫu nhiên 3x3.**

**Write a NumPy program to normalize a 3x3 random matrix.**

![alt text](https://www.w3resource.com/w3r_images/numpy-random-image-exercise-7.svg)

In [8]:
x = np.random.random((3,3))
print("Original Array: ")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin) / (xmax - xmin)
print("After normalization: ")
print(x)

Original Array: 
[[0.8452348  0.42793897 0.06365813]
 [0.42926212 0.09842509 0.74934549]
 [0.27239889 0.37754437 0.43399927]]
After normalization: 
[[1.         0.46608458 0.        ]
 [0.4677775  0.04448311 0.87731298]
 [0.26707649 0.40160646 0.47383852]]


**8, Viết chương trình NumPy để tạo một vectơ ngẫu nhiên có kích thước 10 và sắp xếp nó.**

**Write a NumPy program to create a random vector of size 10 and sort it.**

![alt text](https://www.w3resource.com/w3r_images/numpy-random-image-exercise-8.svg)

In [9]:
x = np.random.random(10)
print("Original array: ")
print(x)
x.sort()
print("Sorted array: ")
print(x)

Original array: 
[0.82557767 0.23783038 0.89269479 0.7163699  0.82936132 0.94097319
 0.35347712 0.30761484 0.22923549 0.91576083]
Sorted array: 
[0.22923549 0.23783038 0.30761484 0.35347712 0.7163699  0.82557767
 0.82936132 0.89269479 0.91576083 0.94097319]


**9, Viết chương trình NumPy để tìm giá trị gần nhất từ một giá trị đã cho trong một mảng.**

**Write a NumPy program to find the nearest value from a given value in an array.**

![alt text](https://www.w3resource.com/w3r_images/numpy-random-image-exercise-9.svg)

In [10]:
x = np.random.uniform(1, 12, 5)
v = 4
n = x.flat[np.abs(x -v).argmin()]
print(n)

5.019266440528683


**10, Viết chương trình NumPy để kiểm tra hai mảng ngẫu nhiên có bằng nhau hay không.**

**Write a NumPy program to check two random arrays are equal or not.**

![alt text](https://www.w3resource.com/w3r_images/numpy-random-image-exercise-10.svg)

In [11]:
x = np.random.randint(0,2,6)
print("First array: ")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array: 
[1 0 1 0 0 1]
Second array:
[0 1 0 1 0 0]
Test above two arrays are equal or not!
False


**11, Viết chương trình NumPy để tạo vectơ ngẫu nhiên có kích thước 15 và thay thế giá trị tối đa bằng -1.**

**Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.**

![alt text](https://www.w3resource.com/w3r_images/numpy-random-image-exercise-11.svg)

In [12]:
x = np.random.random(15)
print("Original array: ")
print(x)
x[x.argmax()] = -1
print("Maximum value replaced by -1: ")
print(x)

Original array: 
[0.15249927 0.48867702 0.80979466 0.99358075 0.5378422  0.8685611
 0.94386177 0.57245027 0.99312908 0.90213788 0.116942   0.52201523
 0.40049679 0.2903337  0.97321809]
Maximum value replaced by -1: 
[ 0.15249927  0.48867702  0.80979466 -1.          0.5378422   0.8685611
  0.94386177  0.57245027  0.99312908  0.90213788  0.116942    0.52201523
  0.40049679  0.2903337   0.97321809]


**12, Viết chương trình NumPy để tìm điểm theo khoảng cách điểm của một vectơ ngẫu nhiên có hình dạng (10,2) đại diện cho tọa độ.**

**Write a NumPy program to find point by point distances of a random vector with shape (10,2) representing coordinates**


In [13]:
a = np.random.random((10, 2))
x, y = np.atleast_2d(a[:, 0], a[:, 1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.73049449 0.55949549 0.35887183 0.41491631 0.45218597
  0.71212724 0.42041925 0.03693036 0.78942568]
 [0.73049449 0.         0.80903198 0.48613881 0.52487008 0.29032746
  0.43372343 0.61593596 0.73657085 0.52434117]
 [0.55949549 0.80903198 0.         0.76979373 0.29976511 0.68583545
  0.47203125 0.21215458 0.59626346 0.47341651]
 [0.35887183 0.48613881 0.76979373 0.         0.50139694 0.21238072
  0.6827914  0.56703189 0.34332587 0.7827519 ]
 [0.41491631 0.52487008 0.29976511 0.50139694 0.         0.3885208
  0.31142327 0.09192359 0.44490168 0.37738117]
 [0.45218597 0.29032746 0.68583545 0.21238072 0.3885208  0.
  0.49215484 0.47371218 0.45356039 0.59449724]
 [0.71212724 0.43372343 0.47203125 0.6827914  0.31142327 0.49215484
  0.         0.36109279 0.73781198 0.10264091]
 [0.42041925 0.61593596 0.21215458 0.56703189 0.09192359 0.47371218
  0.36109279 0.         0.45426702 0.40752831]
 [0.03693036 0.73657085 0.59626346 0.34332587 0.44490168 0.45356039
  0.73781198 0.454267

**13, Viết chương trình NumPy để tìm giá trị thường xuyên nhất trong một mảng.**

**Write a NumPy program to find the most frequent value in an array.**

![alt text](https://www.w3resource.com/w3r_images/numpy-random-image-exercise-13.svg)

In [14]:
x = np.random.randint(0, 10, 40)
print("Original array: ")
print(x)
print("Most frequent value in the above array: ")
print(np.bincount(x).argmax())

Original array: 
[7 7 3 9 5 7 8 7 6 2 5 5 2 4 9 0 1 1 7 3 5 7 7 5 5 7 9 2 2 7 5 2 4 1 8 8 3
 1 2 4]
Most frequent value in the above array: 
7


**14, Viết chương trình NumPy để chuyển đổi tọa độ cartesian sang tọa độ cực của ma trận 10x2 ngẫu nhiên đại diện cho tọa độ cartesian.**

**Write a NumPy program to convert cartesian coordinates to polar coordinates of a random 10x2 matrix representing cartesian coordinates**


In [15]:
z = np.random.random((10,2))
x,y = z[:, 0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.69973731 0.88444156 1.16610337 0.46940625 0.78749867 0.16073433
 0.41202501 1.14300219 0.72316492 0.83321656]
[1.3256121  1.13503407 0.82536886 1.16275431 1.28899523 0.04656443
 1.20543451 0.8777533  0.11386213 1.16555322]


**15, Viết chương trình NumPy để tìm giá trị gần nhất (với một vô hướng đã cho) trong một mảng.**

**Write a NumPy program to find the closest value (to a given scalar) in an array.**



In [16]:
x = np.arange(100)
print("Original array: ")
print(x)
a = np.random.uniform(0, 100)
print("Value to compare: ")
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

Original array: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare: 
2.788285753285469
3


**16. Viết chương trình NumPy để lấy n giá trị lớn nhất của một mảng.**

**Write a NumPy program to get the n largest values of an array.**

![alt text](https://www.w3resource.com/w3r_images/numpy-random-image-exercise-16.svg)

In [17]:
x = np.arange(10)
print("Original array: ")
print(x)
np.random.shuffle(x)
n = 1
print(x[np.argsort(x)[-n:]])

Original array: 
[0 1 2 3 4 5 6 7 8 9]
[9]
