<a href="https://colab.research.google.com/github/bimbeo/Web/blob/master/Sorting_and_Searching.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1, Viết chương trình NumPy để sắp xếp một mảng đã cho có hình 2 dọc theo trục đầu tiên, trục cuối cùng và trên mảng được làm phẳng.**

**Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.**

![alt text](https://www.w3resource.com/w3r_images/numpy-sorting-and-searching-image-exercise-1.svg)

In [2]:
import numpy as np
a = np.array([[10, 40], [30,20]])
print("Original array: ")
print(a)
print("Sort the array along the first axis: ")
print(np.sort(a, axis=0))
print("Sort the array along the last axis: ")
print(np.sort(a))
print("Sort the flattended array: ")
print(np.sort(a, axis=None))

Original array: 
[[10 40]
 [30 20]]
Sort the array along the first axis: 
[[10 20]
 [30 40]]
Sort the array along the last axis: 
[[10 40]
 [20 30]]
Sort the flattended array: 
[10 20 30 40]


**2, Viết chương trình NumPy để tạo một mảng có cấu trúc từ tên sinh viên, chiều cao, lớp và các kiểu dữ liệu của họ. Bây giờ sắp xếp các mảng theo chiều cao.**

**Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.**

![alt text](https://www.w3resource.com/w3r_images/numpy-sorting-and-searching-image-exercise-2.svg)

In [4]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
students = np.array(students_details, dtype=data_type)
print("Original array: ")
print(students)
print("Sort by height")
print(np.sort(students, order='height'))

Original array: 
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


**3, Viết chương trình NumPy để tạo một mảng có cấu trúc từ tên sinh viên, chiều cao, lớp và các kiểu dữ liệu của họ. Bây giờ sắp xếp theo lớp, sau đó chiều cao nếu lớp bằng nhau.**

**Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal.**

![alt text](https://www.w3resource.com/w3r_images/numpy-sorting-and-searching-image-exercise-3.svg)

In [6]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by class, then height if class are equal:")
print(np.sort(students, order=['class', 'height']))

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by class, then height if class are equal:
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


**4, Viết chương trình NumPy để sắp xếp id sinh viên với chiều cao tăng dần của sinh viên từ id sinh viên và chiều cao. In các chỉ số nguyên mô tả thứ tự sắp xếp theo nhiều cột và dữ liệu được sắp xếp.**


**Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.**

![alt text](https://www.w3resource.com/w3r_images/numpy-sorting-and-searching-image-exercise-4.svg)


In [7]:
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])
indices = np.lexsort((student_id, student_height))
print("Sorted indices: ")
print(indices)
print("Sorted data: ")
for n in indices:
  print(student_id[n], student_height[n])

Sorted indices: 
[4 0 5 3 6 1 2]
Sorted data: 
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0


**5, Viết chương trình NumPy để lấy các chỉ số của các phần tử được sắp xếp của một mảng đã cho.**

**Write a NumPy program to get the indices of the sorted elements of a given array.**

![alt text](https://www.w3resource.com/w3r_images/numpy-sorting-and-searching-image-exercise-5.svg)

In [8]:
student_id = np.array([1023, 5202, 6230, 1671, 5241, 4532])
print("Original array: ")
print(student_id)
i = np.argsort(student_id)
print("Indices of the sorted elements of a give array:")
print(i)

Original array: 
[1023 5202 6230 1671 5241 4532]
Indices of the sorted elements of a give array:
[0 3 5 1 4 2]


**6, Viết chương trình NumPy để sắp xếp một mảng phức nhất định bằng cách sử dụng phần thực trước, sau đó đến phần ảo.**

**Write a NumPy program to sort a given complex array using the real part first, then the imaginary part.**



In [9]:
complex_num = [1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j]
print("Original array:")
print(complex_num)
print("\nSorted a given complex array using the real part first, then the imaginary part.")
print(np.sort_complex(complex_num))

Original array:
[(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)]

Sorted a given complex array using the real part first, then the imaginary part.
[1.+2.j 3.-2.j 3.-1.j 3.+5.j 4.-3.j]


**7, Viết chương trình NumPy để phân vùng một mảng nhất định ở một vị trí xác định và di chuyển tất cả các giá trị phần tử nhỏ hơn sang bên trái của phân vùng và các giá trị còn lại ở bên phải, theo thứ tự tùy ý (dựa trên lựa chọn ngẫu nhiên).**

**Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice).**

![alt text](https://www.w3resource.com/w3r_images/numpy-sorting-and-searching-image-exercise-7.svg)

In [10]:
nums = np.array([70, 50, 20, 30, -11, 60, 50, 40])
print("Original array:")
print(nums)
print("\nAfter partitioning on 4 the position:")
print(np.partition(nums, 4))

Original array:
[ 70  50  20  30 -11  60  50  40]

After partitioning on 4 the position:
[-11  30  20  40  50  50  60  70]


**8, Viết chương trình NumPy để sắp xếp số phần tử đã chỉ định từ đầu một mảng nhất định.**

**Write a NumPy program to sort the specified number of elements from beginning of a given array.**

![alt text](https://www.w3resource.com/w3r_images/numpy-sorting-and-searching-image-exercise-8.svg)

In [12]:
nums =  np.random.rand(10)
print("Original array:")
print(nums)
print("\nSorted first 5 elements:")
print(nums[np.argpartition(nums, range(5))])

Original array:
[0.73876372 0.95042229 0.84209505 0.62890701 0.42358798 0.77697797
 0.2009231  0.68045692 0.72815726 0.89350296]

Sorted first 5 elements:
[0.2009231  0.42358798 0.62890701 0.68045692 0.72815726 0.77697797
 0.73876372 0.84209505 0.95042229 0.89350296]
